### ISSUE TITLE
[BUG] BYOD 1.0.1-2 Vst3 crashes REAPER

### ISSUE THREAD

**Issue by SoliDeoGloria2** [Chowdhury-DSP/BYOD#150]
Hi! I'm on Manjaro and BYOD Vst3 crashes REAPER as soon as I try to add it to a FX chain. The Lv2 is working fine (I installed it with Yay from the AUR repository). If you need anything else, just tell me.

Great plugin, by the way. Thanks soo much!!

Greets!

**Comment by jatinchowdhury18** [comment]
Hi, thanks for reporting the issue! I wonder if the crash is related to [this issue](#141). That issue is now fixed on the `main` branch, and in the Nightly Builds, so you may want to give them a try.

Thanks,
Jatin

**Comment by SoliDeoGloria2** [comment]
Hi! Thanks for the reply! I'll build from the main branch and report back as soon as I can...

Greets!

**Comment by SoliDeoGloria2** [comment]
I just couldn't install the main branch build. I'm on Manjaro and the nightlies are in the .deb format. I installed Cmake, but there were some errors and the build from scratch didn ´t prosper. I installed the nightly with debtap, and although it could install it, the Vst3 still crashes REAPER...

**Comment by bukbukXiu** [comment]
Hi! Still crashes reaper for me. I debtapped the last main build.
@SoliDeoGloria2 Did you manage to fix it?
